name: project_e_menu
description: A minimal Flutter digital menu app scaffold
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.4.0
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.2.2
  http: ^1.1.0
  flutter_typeahead: ^5.0.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/menu.json
    - .env
